### ISSUE TITLE
ImageMagick not compatible with Mac OS El Capitan or Sierra

### ISSUE THREAD

**Issue by jessenovotny** [learn-co-curriculum/rails-paperclip-readme#7]
Heads up:

Tests working fine, but file upload does not work in browser.

Errors out "Could not run the `identify` command. Please install ImageMagick."

Looked up the problem online and found "Not compatible with Mac OS 10.11 (El Capitan) or macOS 10.12 (Sierra)." on developers page, http://cactuslab.com/imagemagick/

**Comment by sparshsamir1993** [comment]
Any luck with this? @jessenovotny for someone using Sierra
